### ISSUE TITLE
[BUG]  java.lang.IllegalArgumentException: Equal objects must have equal hashcodes.

### ISSUE THREAD

**Issue by ptal** [chocoteam/choco-solver#1101]
When benchmarking on a MiniZinc instance "peaceable_queens_n8_q3" the new version 4.10.15, had a bug once, see attached.

[org-choco-choco_peaceable_queens_n8_q3.json](https://github.com/user-attachments/files/16960424/org-choco-choco_peaceable_queens_n8_q3.json)

The instance: [n8_q3.json](https://github.com/user-attachments/files/16960453/n8_q3.json)

**Comment by cprudhom** [comment]
Thank you for the bug report.
I assume that it was launched with `-f`, right?

**Comment by jgFages** [comment]
Hi thanks, I guess it comes from IntAffineView which overrides equals but not hashcode. 
I guess the following code would do the job

    @Override
    public int hashCode() {
        return Objects.hash(var.hashCode(), p, a, b);
    }

**Comment by cprudhom** [comment]
Correct, but I want to reproduce it first which I can't right now..

**Comment by ptal** [comment]
```
ptalbot$ minizinc --version                                                                                                                                                 
MiniZinc to FlatZinc converter, version 2.8.5, build 1315240962
Copyright (C) 2014-2024 Monash University, NICTA, Data61
```

```
ptalbot$ java --version
openjdk 11.0.24 2024-07-16
OpenJDK Runtime Environment (build 11.0.24+8)
OpenJDK 64-Bit Server VM (build 11.0.24+8, mixed mode)
```
Note that it works without the -f flag, but not with.

I tried with a more recent version of Java, but same problem:
```
$ java --version
openjdk 22.0.2 2024-07-16
OpenJDK Runtime Environment (build 22.0.2+9)
OpenJDK 64-Bit Server VM (build 22.0.2+9, mixed mode, sharing)
```

**Comment by ptal** [comment]
Here the flatzinc [peaceable_queens.txt](https://github.com/user-attachments/files/16966516/peaceable_queens.txt)

**Comment by cprudhom** [comment]
Actually, the `hashcode()` is defined for all variables and returns the unique ID of a variable (that could be reconsidered but that's another question and seems [OK](https://www.baeldung.com/java-hashcode#understanding-how-hashcode-works)).

The problem is a little more complex than simply defining the hashcode of affine views.
Indeed, the creation of such views here is not related to the (mzn) model but to the method `variableUniqueness(Object[]... vars)`. This method ensures that all variables in the scope of a constraint are unique. If that's not the case, a unique view of a variable that appears twice is created which replaces one occurrence. 
This method is called for `table`, `argmin`, `argmax`, `nValues`, `lexLess` and `lexLessEq`.

Considering Dom/WDeg and variants, I'm not entirely sure that overriding the hashcode method will somehow be correct. Indeed, from the model point of view, those views are different, event if they are equivalent.

So the answer could be to question the existence of `variableUniqueness`.

**Comment by jgFages** [comment]
So you would recommend to remove the equals() method from IntAffineView ?

I actually prefer to remove the equals. This way 100% of variables would the same equals/hashcode relying on their ID, it is easier to apprehend. 

I initially thought the equals was used to somehow optimize a model using several time the same expression, this is why I suggested adding the hashcode. But even if it is the case, one can use a dedicated method for that, no need to rely on the .equals method.

**Comment by cprudhom** [comment]
The `equals` method of affine view exists only to avoid creating the same view more than once (except in `variableUniqueness ` though). But, you are right, I can rename the `equals` method.
