### ISSUE TITLE
Need some support converting Excel Solver 

### ISSUE THREAD

**Issue by bsbiran** [chocoteam/choco-solver#116]
Hello Guys

First I would like to thank you for Choco3, its an excellent Java library!

I am trying to convert a Excel Solver solution to a java one using Choco3

The excel solver is

Solver Parameters:

Set Objective: $D$24 to Max
By Changing Variable Cells: $C$4:$C$23
Subject to the Constraints:
$C$24 = $B$24
$L$24 <= $N$24
$L$25 >= $N$25
(non-negative)
GRG Nonlinear

Can you tell me if its possible to use Choco3 to solve the same problem? I am was looking at the source code and am struggling to convert

Regards
Bobby

**Comment by ByteCode2408** [comment]
Hi, is this topic for interest anymore? I would need some help also to find the best fit values for non linear function using GRG, by using choco solver. Thank you.

**Comment by cprudhom** [comment]
Hi @ByteCode2408,

It is not clear if you want to use GRG or Choco ?

If you want an alternative to Excel tool for GRG, you should have a look at [Ibex](http://www.ibex-lib.org), which is a continuous constraint solver.

If you want to use Choco, you have to convert your model from Excel to Java since there is no other alternative (Choco cannot natively read CSV file).
Best,
CP
