### ISSUE TITLE
iterate over a SetVar is not safe

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco-solver#211]
The way iteration works is not safe at all as it is not context-safe:

```java
        Solver s = new Solver();
        SetVar v = VF.set("foo", new int[]{1,2,3,4}, s);
        assert 1 == v.getEnvelopeFirst();
        System.out.println(v);
        assert 2 ==  v.getEnvelopeNext());
```
Here, v.toString() screws up the code because in the implementation, the counter to indicate the position is unique and not context dependant. A bug that was very tricky to get. Anything in my loop that touch the variable might broke the code.

Iterations deserve that purpose (or passing as a parameter the previous offset similarly to other variables).

CU

**Comment by jgFages** [comment]
@JLiangWaterloo what do you think of the current develop API?
Do you still wish to impose integers of a set to be sorted?

**Comment by JLiangWaterloo** [comment]
Hello @fgFages, I haven't had time to play with it yet
 I'll let you know tomorrow in this thread. Thanks!

**Comment by JLiangWaterloo** [comment]
Hello @jgFages,

Here is my review of the current API.

1. The API forces a lot of Integer boxing and unboxing which is bad for performance ([old article but still true today](http://docs.oracle.com/javase/1.5.0/docs/guide/language/autoboxing.html)). What I mean is that SetVar.getLB.iterator returns an Iterator<Integer> instead of an IntIterator so iterating over the LB or UB will box and unbox an Integer for each iteration. IntVar suffers from the same performance issue.

2. SetVar.getLB returns an ISet which seems to be an inferior version of IntIterableSet? I would recommend using IntIterableSet for SetVar.getLB and SetVar.getUB instead for the following reasons.

i) IntVar.removeValues and IntVar.removeAllValuesBut works with IntIterableSet but not ISet.

ii) As a result, the following lines in PropIntEnumMemberSet.propagate
```java
int ub = iv.getUB();
for (int i = iv.getLB(); i <= ub; i = iv.nextValue(i)) {
    if (!set.getUB().contain(i)) {
        iv.removeValue(i, this);
    }
}
```
can be replaced with
```java
iv.removeAllBut(set.getUB());
```
This should give better performance for large domains as well.

iii) The following lines in PropIntBoundedMemberSet.propagate
```java
int max = ub.iterator().next();
int min = max;
for (int j : ub) {
    max = Math.max(max, j);
    min = Math.min(min, j);
}
iv.updateBounds(min, max, this);
```
can be replaced with
```java
iv.updateBounds(set.getUB().first(), set.getUB().last());
```
This should give better performance assuming first() and last() are efficiently implemented.

iv) The following lines in PropNotMemberSetInt.propagate
```java
for(int v:sv.getLB()){
    iv.removeValue(v, this);
}
```
can be replaced with
```java
iv.removeAll(set.getLB());
```
Again, this should give better performance for large domains.

v) The following lines in PropSetIntValuesUnion
```java
for (int v = X[i].getLB(); v <= X[i].getUB(); v = X[i].nextValue(v)) {
    if (!values.getUB().contain(v)) {
        X[i].removeValue(v, this);
    }
}
```
can be replaced with
```java
X[i].removeAllBut(values.getUB());
```
Again, this should give better performance for large domains.

vi) Set_BitSet.java can be deleted and replaced by IntIterableBitSet (they basically provide the same functionality, but differs in their interface).

vii) Set_FixedArray.java can be deleted and replaced by IntIterableRangeSet.

viii) Set_CstInterval.java can be deleted and replaced by IntIterableRangeSet.

ix) Right now it's kind of annoying that I have to duplicate all of my utility functions, for example computing whether two sets intersect. I would have to implement
```java
boolean intersects(IntIterableSet a, IntIterableSet b);
boolean intersects(ISet a, ISet b);
boolean intersects(IntIterableSet a, ISet b);
```
to cover all the use cases.

**Comment by jgFages** [comment]
The main reason why ISet and IntIterableSet have not yet been merged is that the first one supports unsorted sets whereas the second one requires sorted tests. 

This allows setvars to use bipartite sets and linked lists. 
Linked lists can be adapted to be sorted with a small (but still) overhead. 
However, making the bipartite set sorted would make no sense in terms of performance.

So the questions are : 
1) Should we move towards sorted sets for set var domains (and get rid of Bipartite sets)? 
2) Should we try to maintain both somehow?

**Comment by cprudhom** [comment]
@jgFages You may be interested in those two articles:
[Dancing links](https://en.wikipedia.org/wiki/Dancing_Links) and [Sparse-Sets for Domain Implementation](http://www.cril.univ-artois.fr/~lecoutre/research/publications/2013/sparseTRICS2013.pdf)

**Comment by JLiangWaterloo** [comment]
@jgFages 

Is the sorted requirement for IntIterableSet to support the first and last methods? In the worst case, you can implement these in O(n) for unsorted sets, which is pretty much what PropIntBoundedMemberSet.propagate is doing anyways to compute the smallest and largest element of a set.

**Comment by jgFages** [comment]
Here is what we attempt to do

* Add min() and max() to ISet
* Make IntIterableSet extends ISet
* add removeAll and removeAllBut methods with an ISet in parameters

**Comment by JLiangWaterloo** [comment]
What are your thoughts on the boxing/unboxing issue I mentioned earlier? Seems like an unnecessary overhead that's built into the API.

**Comment by jgFages** [comment]
Yes, I will add another iterators and use it by default inside the API. 
However, the current one will remain too to allow the user writhing for(int i:set) loops.

**Comment by jgFages** [comment]
I added nextInt() to the ISet iterators to avoid auto-boxing:
ISetIterator iter = set.iterator();
while(iter.hasNext()){
   int i = iter.nextInt();
   ... 
}

autoboxed iteration for(int i: set){...} is still supported too but is (almost) never used inside the solver
