### ISSUE TITLE
Chatterbox.printSolution(s) + parallel resolution prints wrong value for objective var

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#363]
The following example:
```java
int n = 10; // number of solvers to use                                                 
ParallelResolution pares = new ParallelResolution();                                    
for (int i = 0; i < n; i++) {                                                           
    pares.addSolver(knapsack());                                                        
}                                                                                       
pares.findOptimalSolution(ResolutionPolicy.MAXIMIZE);                                   
pares.getSolvers().stream().forEach(s -> Chatterbox.printSolutions(s));                 
Chatterbox.printSolutions(pares.getFinder());                                           
Assert.assertEquals(pares.getFinder().getObjectiveManager().getBestSolutionValue(), 51);
```
prints:
```
- Solution #15 found. Solver[Solver-0], 15 Solutions, Maximize v_3 = 51, Resolution time 0,149s, 33 Nodes (221,1 n/s), 37 Backtracks, 4 Fails, 0 Restarts 
	v_0 = 0 v_1 = 0 v_2 = 17 .
- Solution #8 found. Solver[Solver-1], 8 Solutions, Maximize v_3 = 51, Resolution time 0,170s, 24 Nodes (141,3 n/s), 31 Backtracks, 9 Fails, 0 Restarts 
	v_0 = 0 v_1 = 0 v_2 = 17 .
- Solution #9 found. Solver[Solver-2], 9 Solutions, Maximize v_3 = 51, Resolution time 0,171s, 26 Nodes (152,0 n/s), 33 Backtracks, 9 Fails, 0 Restarts 
	v_0 = 0 v_1 = 0 v_2 = 17 .
- Solution #12 found. Solver[Solver-3], 12 Solutions, Maximize v_3 = 51, Resolution time 0,172s, 30 Nodes (174,2 n/s), 37 Backtracks, 7 Fails, 0 Restarts 
	v_0 = 0 v_1 = 0 v_2 = 17 .
- Solution #10 found. Solver[Solver-4], 10 Solutions, Maximize v_3 = 51, Resolution time 0,173s, 28 Nodes (161,6 n/s), 37 Backtracks, 9 Fails, 0 Restarts 
	v_0 = 0 v_1 = 0 v_2 = 17 .
- Solution #1 found. Solver[Solver-5], 1 Solutions, Maximize v_3 = 51, Resolution time 0,174s, 7 Nodes (40,1 n/s), 11 Backtracks, 6 Fails, 0 Restarts 
	v_0 = 0 v_1 = 0 v_2 = 14 .
- Solution #10 found. Solver[Solver-6], 10 Solutions, Maximize v_3 = 51, Resolution time 0,175s, 26 Nodes (148,3 n/s), 31 Backtracks, 7 Fails, 0 Restarts 
	v_0 = 0 v_1 = 0 v_2 = 17 .
- Solution #1 found. Solver[Solver-8], 1 Solutions, Maximize v_3 = 51, Resolution time 0,176s, 5 Nodes (28,4 n/s), 7 Backtracks, 4 Fails, 0 Restarts 
	v_0 = 0 v_1 = 0 v_2 = 17 .
- Solution #1 found. Solver[Solver-9], 1 Solutions, Maximize v_3 = 51, Resolution time 0,177s, 3 Nodes (16,9 n/s), 3 Backtracks, 2 Fails, 0 Restarts 
	v_0 = 0 v_1 = 0 v_2 = 17 .
- Solution #15 found. Solver[Solver-0], 15 Solutions, Maximize v_3 = 51, Resolution time 0,178s, 33 Nodes (185,0 n/s), 37 Backtracks, 4 Fails, 0 Restarts 
	v_0 = 0 v_1 = 0 v_2 = 17 .
```
But Solver[Solver-5] outputs a wrong value for the objective. 
Indeed, it prints the best known value (found by another thread) instead of the current solution value (`42`).

This comes from `ObjectiveManager.toString()`:
```java
@Override
public String toString() {
    String st;
    switch (policy) {
        case SATISFACTION:
            return "SAT";
        case MINIMIZE:
            st = "Minimize";
            break;
        case MAXIMIZE:
            st = "Maximize";
            break;
        default:
            throw new UnsupportedOperationException("no objective manager");
    }
    if (intOrReal) {
        return String.format(st + " %s = %d", this.objective.getName(), getBestSolutionValue());
    } else {
        return String.format(st + " %s = %." + getNbDecimals() + "f", this.objective.getName(), getBestSolutionValue());
    }
}
```
 which does not consider the current value at all.

**Comment by cprudhom** [comment]
I suggest to print both objective domain and best known bound:
```java
return String.format(st + " %s = %d", this.objective.getName(), getBestSolutionValue());
```
becomes:
```java
return String.format("%s %s %s %d",
                    st, this.objective, policy == ResolutionPolicy.MINIMIZE ?" <= " :" >= ", getBestSolutionValue());
```

**Comment by jgFages** [comment]
I believe this problem is solved :: 

                int n = 10; // number of solvers to use
		ParallelPortfolio pares = new ParallelPortfolio();
		for (int i = 0; i < n; i++) {
		    pares.addModel(knapsack());
		}
                while (pares.solve());
		Assert.assertEquals(pares.getBestModel().getSolver().getBestSolutionValue(), 51);

Prints:
- Solution #1 found. Model[ModelT-4], 1 Solutions, Maximize v_3 = 26, Resolution time 0,032s, 4 Nodes (126,9 n/s), 0 Backtracks, 0 Fails, 0 Restarts 
	v_0 = 3 v_1 = 2 v_2 = 0 .
- Solution #1 found. Model[ModelT-1], 1 Solutions, Maximize v_3 = 0, Resolution time 0,031s, 4 Nodes (126,9 n/s), 0 Backtracks, 0 Fails, 0 Restarts 
	v_0 = 0 v_1 = 0 v_2 = 0 .
- Solution #1 found. Model[ModelT-5], 1 Solutions, Maximize v_3 = 51, Resolution time 0,032s, 2 Nodes (62,3 n/s), 0 Backtracks, 0 Fails, 0 Restarts 
	v_0 = 0 v_1 = 0 v_2 = 17 .
- Solution #1 found. Model[ModelT-2], 1 Solutions, Maximize v_3 = 20, Resolution time 0,031s, 4 Nodes (124,4 n/s), 0 Backtracks, 0 Fails, 0 Restarts 
	v_0 = 0 v_1 = 5 v_2 = 0 .
- Solution #1 found. Model[ModelT-7], 1 Solutions, Maximize v_3 = 30, Resolution time 0,032s, 4 Nodes (125,3 n/s), 0 Backtracks, 0 Fails, 0 Restarts 
	v_0 = 1 v_1 = 3 v_2 = 4 .
- Solution #1 found. Model[ModelT-9], 1 Solutions, Maximize v_3 = 30, Resolution time 0,031s, 4 Nodes (127,5 n/s), 0 Backtracks, 0 Fails, 0 Restarts 
	v_0 = 1 v_1 = 0 v_2 = 8 .
- Solution #1 found. Model[ModelT-6], 1 Solutions, Maximize v_3 = 28, Resolution time 0,033s, 4 Nodes (122,6 n/s), 0 Backtracks, 0 Fails, 0 Restarts 
	v_0 = 0 v_1 = 4 v_2 = 4 .
- Solution #1 found. Model[ModelT-0], 1 Solutions, Maximize v_3 = 0, Resolution time 0,032s, 4 Nodes (123,8 n/s), 0 Backtracks, 0 Fails, 0 Restarts 
	v_0 = 0 v_1 = 0 v_2 = 0 .
- Solution #1 found. Model[ModelT-3], 1 Solutions, Maximize v_3 = 28, Resolution time 0,032s, 3 Nodes (94,1 n/s), 0 Backtracks, 0 Fails, 0 Restarts 
	v_0 = 4 v_1 = 1 v_2 = 0 .
- Solution #1 found. Model[ModelT-8], 1 Solutions, Maximize v_3 = 19, Resolution time 0,032s, 4 Nodes (126,8 n/s), 0 Backtracks, 0 Fails, 0 Restarts 
	v_0 = 2 v_1 = 1 v_2 = 1 .
