### ISSUE TITLE
MeasureRecorder and IMeasureRecorder maniability

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco-solver#409]
I want to combine some measurements (for problems solved in multiple stages).
It is currently not easy to aggregate measures because of the API that is strongly coupled with its online usage (inc* methods).

Should be great to be possible to directly set a value.

Aside, IMeasure has a lot of methods so it is not very nice to re-implement if I just want to add setters.
Are all the methods required at the interface level ?

**Comment by arnaud-m** [comment]
Hello,

I have the same kind of requests to combine/aggregate several measures. 
It has been started.

**Comment by cprudhom** [comment]
Honestly, I can't see clearly what your needs are.
At the beginning, the measures recorder was there to record measures (like solution count, node count, etc), that is why it provides both getters and incrementers (no setters since it was maintained incrementally). 

Then, we split it into `IMeasures` (an interface for getters only) and its concrete implementation `MeasuresRecorder` with the addition of incrementers (but, without interface for the incrementers/setters.) It also provides pretty `toString...()` methods.
Then `Solver`, which implements `Measures`, binds the calls to its internal instance of `MeasuresRecorder`. 

So, what else ?

**Comment by fhermeni** [comment]
I did not see the fields that are directly available in the implementation so I may have spoke to fast on this one. I tell you more tomorrow

**Comment by arnaud-m** [comment]
For instance, I need to perform this operation on two measures m1 = m1 + m2.
The meaning of + differ depending on the metric.

But, I simply need to add the method to the concrete implementation to the `MeasuresRecorder.`

**Comment by fhermeni** [comment]
@arnaud-m fields in MeasureRecorder are public so you can manipulate them the way you want.
On my side, after trying to work with MeasureRecorder, it was able to aggregate the data the way I want.
