### ISSUE TITLE
Continuous expressions: improvements

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#417]
- [ ] assign one unique ID to variables in functions in such way that expressions can be compacted. Thus, expressions could be declared together in one instance of Ibex
- [ ] deal with constants: they can be replaced in expressions to Ibex by their value instead of instantiated variables
- [ ] deal with AST constraint
- [ ] throw a clearer message when the VM is not correctly set

**Comment by mwahbi** [comment]
Hey @cprudhom, 
By the way, I am wondering why the ID of a variable is simply its index on the model array of variables. This, will simplify a lot of things when using variables.

**Comment by cprudhom** [comment]
I believe you mean "why the ID of a variable is NOT simply its index on the model array of variables".
Well, considering that anyone can remove a variable, basing the ID on the position of the variable in the model array would require to either allow null in the middle of the array (not really a good idea) or to update all structures based on the ID anytime a variable is removed (which may be complex to do).

I understand that removing a variable is a very rare action but we made that assumption from the beginning of the development, now we are a little stuck to that.

**Comment by mwahbi** [comment]
Thanks Charles, 
Okay I see, I didn't think about the variable removal. 
I am asking because I am using several models/solvers (having some common variables) but only a solver associated to a model can define a strategy on each variable, i.e., only one solver (that own a variable) can make decisions on this variable. So, each solver needs to store (indexes of) variables of other solvers in order to apply decisions made by their owners.

**Comment by cprudhom** [comment]
If you are sure that the modeling method (which creates, feeds and returns the model) applies the same instructions in the very same order then the IDs are ensured to be same in all models.
