### ISSUE TITLE
Migration script from 3.3.3 to 4.0.0: useful ?

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#427]
I am considering writing a script (based on [spoon v5.1.1](https://github.com/INRIA/spoon)) that migrates code from Choco-3.3.3 to Choco-4.0.0.
I made that choice because it is in Java and active (and also because I couldn't find tons of library doing code migration).

Considering that I'm not a spoon-expert, I managed to prototype a first version (evaluated it on some of my own projects) that transforms:
- `Solver solver = new Solver("a name")` into `Model solver = new Model("a name")`, (note: the variable's name does not change !)
- variables creation (e.g. `IntVar i = VariableFactory.enumerated("I", 0, 10, solver);` into `IntVar i = solver.intVar("I", 0, 10, false);`
- constraints declaration:`solver.post(IntConstraintFactory.a_cstr(...));` into `solver.post(solver.a_cstr(...));`

I'm pretty sure I can:
-  transform 'solver.method()` to `solver.getSolver().method()` (recall that the variable's name remains the same),
- remove calls to `Chatterbox` by calls to `solver.getSolver()`,
- replace `SearchStrategy` by `Search`,
but I didn't try yet.

Issues:
- I was not able to maintain comments in output classes,
- I was not able to remove reference to `IntConstraintFactory` for reified constraints (since there is no direct reference to the model)

I'm considering a script that does the worst of the work (variables and constraints mainly).

Do you (users) think such a script (with its limits) would be helpful ? Or I give up right now ?

**Comment by fhermeni** [comment]
Hi

I can test your script on btrplace codebase if you want (but not this week). Don't forget about the VF and the ICF shortcuts. Of course, you can also test by your own (just for fun😀)

However, it your script removes the comment, I might prefer to migrate the code manually. Depending on the amount of work of course.

Sent from a mobile




On Mon, Jun 27, 2016 at 1:36 PM +0100, "cprudhom" <notifications@github.com<mailto:notifications@github.com>> wrote:


I am considering writing a script (based on spoon v5.1.1<https://github.com/INRIA/spoon>) that migrates code from Choco-3.3.3 to Choco-4.0.0.
I made that choice because it is in Java and active (and also because I couldn't find tons of library doing code migration).

Considering that I'm not a spoon-expert, I managed to prototype a first version (evaluated it on some of my own projects) that transforms:

  *   Solver solver = new Solver("a name") into Model solver = new Model("a name"), (note: the variable's name does not change !)
  *   variables creation (e.g. IntVar i = VariableFactory.enumerated("I", 0, 10, solver); into IntVar i = solver.intVar("I", 0, 10, false);
  *   constraints declaration:solver.post(IntConstraintFactory.a_cstr(...)); into solver.post(solver.a_cstr(...));

I'm pretty sure I can:

  *   transform 'solver.method()tosolver.getSolver().method()` (recall that the variable's name remains the same),
  *   remove calls to Chatterbox by calls to solver.getSolver(),
  *   replace SearchStrategy by Search, but I didn't try yet.

Issues:

  *   I was not able to maintain comments in output classes,
  *   I was not able to remove reference to IntConstraintFactory for reified constraints (since there is no direct reference to the model)

I'm considering a script that does the worst of the work (variables and constraints mainly).

Do you (users) think such a script (with its limits) would be helpful ? Or I give up right now ?

**Comment by cprudhom** [comment]
Yep, I need to find a way to keep comments otherwise it cannot be a solution at all !

**Comment by cprudhom** [comment]
Finally, we listed the most common modifications since the script was not satisfying.
See [release-4.0.0](https://github.com/chocoteam/choco-solver/releases/tag/untagged-7b156e8b13eed9bd1ba7) for more details
