### ISSUE TITLE
Regression: reifyWith(ONE) (or ZERO) does not work

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#428]
```java
Model m = new Model();
IntVar row[] = m.intVarArray("r", 3, 0, 5);
BoolVar one = m.boolVar(true);
m.sum(row, "=", 5).reifyWith(one);
```
throws an error.

There are two options to fix the issue:
- allowing `FixedBoolVarImpl` to define a not,
- by-passing the reification by posting directly the constraint (or its opposite)

(Related to: #402)

**Comment by cprudhom** [comment]
I vote for the first option, it is a more generic patch which includes the second option.

**Comment by jgFages** [comment]
I vote for by-passing the reification to post directly the constraint (or its negation) in case the boolean equals 1 (or 0).

With such by passing, the code of your example will work. However, this code will still fail :  

``m.sum(row, "=", 5).reifyWith(one.not());`` 

because one.not() has first to be created before knowing whether it is a constant or not, so yes FixedBoolVarImpl should definitely define not() too.

**Comment by cprudhom** [comment]
Ok, we both agree `FixedBoolVarImpl ` should define `not`.

If we by-pass the reification, the fixed boolean variable should be attached to the constraint but no reification should be posted, otherwise an error will be thrown, since a constraint cannot be both posted and reified.
If you agree, I can fix the issue.

**Comment by cprudhom** [comment]
That does not fix the issue of multiple occurrences of ONEs and ZEROs in a model...

**Comment by jgFages** [comment]
I agree (to both comments)
