### ISSUE TITLE
Better filtering for set intersection

### ISSUE THREAD

**Issue by JLiangWaterloo** [chocoteam/choco-solver#448]
For example, consider the following example:

```java
        Model m = new Model();
        SetVar s1=m.setVar("s1", new int[]{1,2,3}, new int[]{0,1,2,3,4,5,6});
        SetVar s2=m.setVar("s2", new int[]{}, new int[]{0,1,2,3,4,5,6});
        Constraint c = m.intersection(new SetVar[]{s1,s2}, m.setVar());
        c.post();
        
        m.getSolver().propagate();
        System.out.println(s1+ " intersect " + s2 +" is empty");
```

The values 1, 2, and 3 should be removed from s2, but the current propagator does nothing.

**Comment by jgFages** [comment]
Yes there is no filtering from the result to the input sets regarding values in some input LB and not in the result UB. The reason is that it could become very time consuming for getting no inference when intersecting many sets (it is allowed to have same values on n-1 sets, where n is the number of sets to intersect). I believe it would make sense to add a complementary propagator to do it in the binary case. Can you do it?
