### ISSUE TITLE
Solver.hasReachedLimit() method doesn't exist althought mentioned in user guide

### ISSUE THREAD

**Issue by gregy4** [chocoteam/choco-solver#479]
When I inspected history of master branch, the method was removed on 27th February 2016 in a commit named "remove deprecated code".

Since the method wasn't marked as deprecated in 3.3.3 and simply disapperated in next releases it is the error and my advice is to bring it back. For me the method cannot be mixed with another stop criterias since it means that no enough time (or possibly number of nodes) were given for solution task.

**Comment by cprudhom** [comment]
That's a mistake.
However, the method has been replaced by the method named `Solver.isStopCriterionMet()` (since limit were renamed criterion so far, both method act similarly).
Moreover, you can also call `Solver.getState()` which returns one of those states:
- `NEW`: when the problem is established but the resolution has not been triggered yet ;
- `RUNNING`: when the solver is searching for a solution ; 
- `TERMINATED`: the search ends normally, a solution is found or the entire search tree was explored without finding any solution ;
- `STOPPED` : the search was stopped by a limit ; 
- `KILLED` : the resolution was killed from the outside (eg, thread interruption, JVM killed)

**Comment by gregy4** [comment]
Thanks for the explanation.
Unfortunatelly there's a lot of other classes and methods not present in 4.0.0 and not mentioned in notes like ChatterBox or SearchLoop.getLastDecision() method that it is hard if not impossible to update my code.

**Comment by cprudhom** [comment]
Sorry for that, I mainly focus on what has changed in the `Model` since most of the modifications are related to this part.
If you want to complete the notes, tell me.

**Comment by cprudhom** [comment]
Could you tell me what let you think that updating your model to 4.0.0 is not possible ?

**Comment by gregy4** [comment]
Primary it is about time spent with every compilation problem. For this issue it took me about 2 hours inspecting year back in history to found out what is going on + look at different versions of user guide. Other issues (originally more than 100 errors) took about 30minutes for each if not repeated since no deprecated method exists in the code of choco solver. Now after three days of work I'm able to compile my code (with some exceptions) and solver performance is for my problem about 30% slower compared to version 3.3.3. Since versions 3.3.3, 4.0.0 and 4.0.1 are incompatible between each other it can be very big problem to find out where's the problem, clever usage of deprecated methods could help me to go back in history of develop branch to localize the problem.

**Comment by cprudhom** [comment]
You're right, we missed a point, while releasing 4.0.1, about DecisionOperator. It may painful to find the right call, since we forget to keep the deprecated methods; I'll pay attention to not reproduce this again in the future.
About 3.3.3 to 4.0.0, since we totally change the API, we didn't want to keep deprecated ones, since most of them (from Model) were deprecated. I agree that is a radical choice which makes hard  moving from 3 to 4. In June, I started a [discussion](https://github.com/chocoteam/choco-solver/issues/427) on that very point and had very few feedbacks, so I decided by myself.
About slower code, when you find out what goes wrong, could you tell me more about it ? 
On our benchmarks we did not notice any major loss of performances.

**Comment by gregy4** [comment]
Well I found the problem with performance just today. Since number of solutions, number of explored nodes and number of backtracks is same I hope that only performance of individual propagator causes the performance problem.

**Comment by fhermeni** [comment]
@gregy4 could you measure the slowdown ?

**Comment by gregy4** [comment]
I already wrote it, for first test problem after refactoring it is about 30%.
At first I thought that the problem is with TwoBucketPropagationEngine but a profiler showed me that implementation of graph cumulative was changed a lot between 3.3.3 and 4.0.1. Time and number of invocations is very different for demanding methods - in 3,3,3 most time was used by TimeCumulFilter and NRJCumulFilter, in 4.0.1 are demandings methods populate(int) and populate(int, int). Unfortunatelly most commits in this area are without issue number so it is hard to find details about it.
