### ISSUE TITLE
significant slowdown of incremental cumulative in choco4 versions compared to choco3

### ISSUE THREAD

**Issue by gregy4** [chocoteam/choco-solver#483]
This week I was moving my code from choco 3.3.3 version to choco 4 version. After conversion I experienced significant slowdown of my testing problem - about 30% compared to choco3.

Thanks to a profiler I probably found a reason for that. Methods PropGraphCumulative.propagate(int) and PropGraphCumulative.propagate(int, int) takes much more time than in choco3. In both cases this is caused by self time of methods, in choco3 the methods took nearly no time. With methods called inside it means in my case that first method takes twice much time, second method is even worse.

I found commit that on April 9th 2016 named 'update cumulative' that is probably reason for this slowdown.

**Comment by jgFages** [comment]
This enabled to gain on other benchmarks. If it is less efficient on yours, i suggest you to create your own cumulative using the old propagators.

**Comment by gregy4** [comment]
Can you tell me more about the benchmarks ?  My problem is mostly classical scheduling problem and I reported in choco3 probably most issues related to cumulative constraint since nobody else had such demanding problem in this area.

Is it available some description of ideas that old and new cumulative was based on ?

From first look on differences between the versions I'm not sure that new implementatin of cumulative is 100% correct. For example old one checks whether toCompute already contains element that should be added and new one doesn't check it. propagate(int, int) is called twice as much althought number of explored nodes and backtracks is equal for both choco solver versions.

**Comment by jgFages** [comment]
It was based on minizinc instances (there are many problems related to scheduling, similar from a global view but the best way to solve them can be quite different). Some require more filtering, some less...

The main difference between the two versions is the propagation configuration (algorithms are more or less the same). In the old version, propagators where called less often (i.e. the propagation stops before achieving a fix point). In particular, the getPropagationConditions method was different: it skipped half of propagations related to bound modifications (which explains why you now have twice more calls). This was faster on problems with many variables and where there was no much deductions to perform anyway (if you have nothing to filter, there is no need to call the algorithm). However, it was also counter productive on problems where missing one deduction could lead to trashing. 

The new approach skips much less propagations. Whether or not these new propagations are profitable depends on the problem. 

If you want to contribute to improve it, I believe the best thing to do is to create a new propagator that would ensure the fixpoint (inside itself). This would enable to use only one propagator instead of the two we currently use to make a ping pong. It would save time and be much "cleaner" than the old trick.

**Comment by cprudhom** [comment]
@gregy4 Is it ok for you if I close this issue ?

**Comment by gregy4** [comment]
Yes, it is ok for me. More investigation in this area is needed, hope I near future improve performance of cumulative constraint.
