### ISSUE TITLE
Find next solution?

### ISSUE THREAD

**Issue by fokdiekul** [chocoteam/choco-solver#511]
Hi,

For my thesis I'm using the choco solver to perform graph coloring.  However just finding a correct graph coloring isn't enough. Therefor I was wondering if it was possible to get a result, check if it's OK, if not get a next result, etc...

Thanks in advance!

Nicholas

**Comment by cprudhom** [comment]
Well, if your model is correct, any result should be a solution, otherwise, you need to change the model.
Otherwise, you should call `solver.solve()` which returns `true` if a solution is found (the solver is then under a "solution-state", i.e., all variables should be instantiated) or `false` if no (new) solution is found. Have a look at the [documentation](http://choco-solver.readthedocs.io/en/latest/?badge=latest) and [javadoc](http://www.choco-solver.org/apidocs/index.html) for more details and alternatives.

**Comment by fokdiekul** [comment]
Thank you!
