### ISSUE TITLE
Cumulative constraint not able to prune more complex tasks

### ISSUE THREAD

**Issue by eramol** [chocoteam/choco-solver#562]
I have 4 tasks.
As I am scheduling jobs, I am instantiating them from lower bound.
First I place A.
Then I place B, but the placement fails.
Then there are len(A) - len(B) iterations where B is placed 

### Expected behavior
![image](https://user-images.githubusercontent.com/6906865/31446816-c0663bb0-aea0-11e7-92f6-8dfeb70bba78.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/6906865/31445767-0d96a5fc-ae9f-11e7-8125-6206a2e25763.png)

### Minimal Working Example

Experienced with choco-solver-_*{3.3.3 - 4.0.5}*_

```java
public class BasicPlayground {
	public final static int MAXTIME = 10000;
	
	public static void main(String[] args) {
		Model model = new Model();

		TTask a = new TTask("taskA", model, 800);
		TTask b = new TTask("taskB", model, 10);
		TTask c = new TTask("taskC", model, 10);
		TTask d = new TTask("taskC", model, 10);
		
		model.post(model.arithm(b.getEnd(), "=", c.getStart()),
				model.arithm(b.getEnd(), "=", d.getStart()),
				model.cumulative(
						new Task[]{a.getTask(), b.getTask(), c.getTask(), d.getTask()},
						model.intVarArray("", 4, 1, 1),
						model.intVar(2),
						false,
						Cumulative.Filter.HEIGHTS)
		);
		
		
		Solver solver = model.getSolver();
		solver.setSearch(Search.minDomLBSearch(a.getStart(), b.getStart(), c.getStart(), d.getStart()));
		Solution solution = solver.findSolution();
		solver.printStatistics();
	}	
}

@Data
class TTask {
	private final IntVar start;
	private final IntVar end;
	private final IntVar duration;
	private final Task task;
	
	public TTask(String taskName, Model model, int iduration) {
		this.start = model.intVar(taskName + " start", 0, BasicPlayground.MAXTIME);
		this.end = model.intVar(taskName + " end", 0, BasicPlayground.MAXTIME);
		this.duration = model.intVar(taskName + " duration", iduration, iduration);
		this.task = model.taskVar(start, duration, end);
	}
}
```

**Comment by cprudhom** [comment]
Hi,

The reason why cumulative fails at filtering more values from the domain of `B_s` comes from the fact that it does not handle external relations between tasks.

There are many options:
1. The sweep-based algorithm for cumulative first compute the mandatory parts, builds a profile and then filters values from this profil. It can be adapted to build a profile that takes into account the relation between tasks. The filtering part can also be adapted to better deal with the resources consumed (this is a quick answer, I know it is possible to do but I don't know how to do for now)
2. Since you are trying to place complex objects in a box with a cumulative constraint, you could use the Geost constraint instead (from [choco-geost](https://github.com/chocoteam/choco-geost)). This is a complex library very powerful (but there are some known bugs in it) which would fit your need.
3.You can (I don't know what is possible for you) aggregate tasks C and D to a new one that has a height of 2. That would "push" this task to the end of A together with B.  
4. There could be another modeling trick to capture the case, kind of dual view of the constraint ...

Hope it helps,

**Comment by eramol** [comment]
Thank you for the reply. 

Number 1 doesn't solve the problem unfortunately. I tried experimenting with the algorithms for filtering, but none did provide us with the result.

One actually didn't work at all, which was **DisjunctiveTaskIntervalFilter**. It actually stated that there is _no solution_ when this filter was used. I am not sure whether to report it as a bug or if it is intended functionality, but it seems weird.

I will check out number 2.

I proposed 3 today as a solution to our problem. It is a possible and useful dual technique, however the implementation might be tricky, as one has to compute a profile for every hard-binded group.

**Comment by jgFages** [comment]
Disjunctive is the special case where capacity = 1, so I would not call it a bug but maybe documentation could be improved on this

**Comment by eramol** [comment]
This is not disjunctive, the capacity on the pictures is 2

**Comment by jgFages** [comment]
its what i say, disjunctive is for capacity 1, so you should NOT manually use DisjunctiveTaskIntervalFilter if capacity is not equal to 1

**Comment by eramol** [comment]
Oh, right, thank you for the clarification

**Comment by cprudhom** [comment]
> The sweep-based algorithm for cumulative first compute the mandatory parts, builds a profile and then filters values from this profil. It can be adapted to build a profile that takes into account the relation between tasks. The filtering part can also be adapted to better deal with the resources consumed (this is a quick answer, I know it is possible to do but I don't know how to do for now)

I was not clear. I didn't mean to select another filtering algorithm(s) but to tweak the sweep-based one.

**Comment by eramol** [comment]
Thank you. I think it will be the best to detect hardly connected components (with fixed distances) from the data and make a profile. From this profile define through dual programming new tasks, which would share the variables of the original tasks but would have heights of the segments in between. Those, mixed with the non-transformed original tasks would be subject to another cumulative with the same capacity.

**Comment by jgFages** [comment]
Absolutely!
