### ISSUE TITLE
Arc consistant AllDiff is weaker than it should

### ISSUE THREAD

**Issue by xgillard** [chocoteam/choco-solver#606]
Problem: The arc consistant alldiff is weaker than it should.

The example below reproduces a simple case where the value `30` has no support in the domain of x0. Yet, choco alldiff ac propagator does not prune it.
```java
    @Test
    public void replay() throws ContradictionException {
        Model choco = new Model();

        IntVar x0 = choco.intVar(29,31, true);
        IntVar x1 = choco.intVar(30);

        choco.post(choco.allDifferent(new IntVar[]{x0, x1}, "AC"));
        choco.getSolver().propagate();

        Assert.assertFalse(x0.contains(30));
    }
```

**Comment by xgillard** [comment]
Context: as usual, I was experimenting with solvercheck and here is what it came up with.

**Comment by cprudhom** [comment]
Hi,

thanks again for the bug detection.
Indeed, in Choco, bounded variables does not value removals in the middle of the domain.
That's a behaviour we always have in mind while developing enumeration strategy and constraints.
In the past, we had considered dynamically adapting the way domains are managed during the search but we finally made the choice of a simpler architecture (ie, no domain object in a variable) for performance purposes mainly (and also because Choco is based on trail).

Obviously, `IntervalIntVarImpl` should return false when the value removal cannot be done.

I'll have a look soon.

Best,
CP

**Comment by xgillard** [comment]
> Obviously, `IntervalIntVarImpl` should return false when the value removal cannot be done.

That's indeed what it does. Imho the best way to "fix" this "issue" is then probably to just update the doc. I think that explaining in `IVariableFactory` that setting the `boundedDomain` flag  true means that no update are possible in the middle of the domain would be ok. Having a note in `IntervalIntVarImpl` which tells about this (and that it is a deviation from the `IntVar` interface would be nice too).
