### ISSUE TITLE
Which kind of propagation for function scalar() ? 

### ISSUE THREAD

**Issue by MehdiZrhal** [chocoteam/choco-solver#629]
Hello,
 
The function scalar( IntVar[] vars, coeffs , '' = " , IntVar sum ) seems to be propagating AC or BC depending on the number of variables (vars.length). Here is an example of my model : 

            Model model = new Model("Test");
		Random random = new Random();		
		int n = 25;
            int[] coeffs = new int[n];

		for (int i = 0 ; i < n ; i++) {
	              coeffs[i] =random.nextInt(100);
		}

		BoolVar[] vars = model.boolVarArray("vars",n);
		IntVar sum = model.intVar("sum", 0, 1000 );
		
		model.scalar(vars, coeffs, "=", sum ).post(); 
		
            Solver solver = model.getSolver();
		solver.showDecisions();

The domain of the variable sum for n=25 is always an interval, which suggests that the level of propagation is BC, but the domain of sum for n=10 is no longer an interval which suggests that AC is used. Is there a way to enforce AC for larger values of n ? 

Thank you in advance.

**Comment by cprudhom** [comment]
Hi,

On some cases, including scalar, we can check the cardinality of domains in order to consider expressing the constraint with a table constraint. There are different conditions. For scalar there are three conditions:
1. the operator should be "=="
2. the resulting variables should be enumerated
3. the domains cardinality should not exceed 10000. 

You can either modify the last option :
```java
Model model = new Model(new DefaultSettings().setMaxTupleSizeForSubstitution(656));
```

Or directly declare a table constraint that relies on tuples generated manually or thanks to `TupleFactory.generateTuples(TupleValidator filter, boolean feasible, int[]... doms)`
where:
- `filter` is a tuple validator, it takes a tuple as input and should `true` if the tuple is valid, `false` otherwise.
- `feasible` indicates wether the generated tuples are feasible, when set to `true`, or not.
- `doms` are the current domain of the variables.

Example for `absolute` operator: 

```java
public static Tuples absolute(IntVar VAR1, IntVar VAR2) {
    return generateTuples(values -> values[0] == Math.abs(values[1]), true, VAR1, VAR2);
}
```
