### ISSUE TITLE
no-dep.jar isn't getting release to maven repository

### ISSUE THREAD

**Issue by yunglin** [chocoteam/choco-solver#641]
In the maven repo, it only contains fat jar, the no-dep jar is missing from the release. 
 
maven repo: https://repo1.maven.org/maven2/org/choco-solver/choco-solver/4.10.0/
* Choco-solver version: 4.10.0
* Java version:
* Link to your project:

**Comment by cprudhom** [comment]
Hi,

This issue is redundant with #616 
I'm currently working on it, that will be part of the next release.

Best

**Comment by yunglin** [comment]
@cprudhom I have a pull request to solve this issue already. Can you take a look at it?

https://github.com/chocoteam/choco-solver/pull/642

**Comment by cprudhom** [comment]
I did, but since I work on a multi-module version of the current project (which only unify existing modules in a single project, and will impact users), I already fix that (you can have a look at the `modules` branch that I plan to merge very soon). That's why I don't want to integrate new PR before the next release (which will fix this issue and #616).
Best,
CP
