### ISSUE TITLE
How to build predecessor and successor vectors with Choco

### ISSUE THREAD

**Issue by diegomartinop** [chocoteam/choco-solver#690]
Hi.

I'm using Choco Solver in Java and I'm working with a problem in which I have a binary vector like this:

v = 0 0 0 1 0 1 0 0 1

and I wish to create two new vectors from this binary vector with the respectives predecessor and successor in which v is true (i.e., v[i] = 1). The results shoud be like this:

pred = -1 -1 -1 0 -1 3 -1 -1 5
succ = -1 -1 -1 5 -1 8 -1 -1 0

in which -1 indicates that v[i] = 0 and the others numbers are the respectives predecessor and successor nodes regarding the vector v.

I tried to use inverseChanneling() and reification() but without success.
Anybody has any idea of how to do that?

Thank you.

**Comment by cprudhom** [comment]
Hi,

You can have a look at what is done for the TSP: https://choco-solver.org/tutos/traveling-salesman-problem/
That may be a source of inspiration.

Hope that helps,
CP

**Comment by diegomartinop** [comment]
Yes, it helps. But I need something that allows me to add only the successor/predecessor of a node if the boolean variable associated is true. In the case of TSP, he computes the successor of all the cities. 

if  v[i] = true then computes successor

**Comment by cprudhom** [comment]
In the TSP, we force all cities to be visited (that is ensured by the subCircuit constraint).
That constraint specifies that a *node_i* loop over itself if *node_i = i*.
So in your case, you can reify this state.

On the other hand, inverseChanneling should also work. It states that "X_i = j <=> Y_j = i".
Again, you should not consider "-1" as the unconnected state but "X_i = i" (a loop over itself).

**Comment by diegomartinop** [comment]
Do you have some example of code? I don't see how to reify this constraint in order to do what I'm supposed to do.

About inverseChanneling constraint, the problem is that if
pred[i] = j <=> v[j] = i which is not true in this case and does not compute the predecessor

**Comment by diegomartinop** [comment]
Would it be something like this:

model.reification(v[i], model.subCircuit());

?

**Comment by cprudhom** [comment]
Could you describe the problem you want to model and solve?

**Comment by diegomartinop** [comment]
Yes.
It's VRP problem.

I have a vector b that indicates if the driver needs to make a pause in the customer i.

Then I use reification to state that if b[i] > 0 (there is a pause), pause[i] = 1:
model.reifyXgtC(b[i], 0, pause[i]);

For example, considering 5 customers, there is a pause in customers 1, 3 and 4.
Then, the binary vector pause is like this:
0 1 0 1 1 0  (customer 0 is fictif)

I need now a predecessor vector saying that the predecessor of customer 1 is 0 (fictif), that the predecessor of 3 is 1 and the prodecessor of 4 is 3.
That is, create the pred vector only with those customers in which pause is true.

**Comment by cprudhom** [comment]
Ok. I have no turnkey solution for you, I never modelled a VRP in CP.
I think the main difficulty comes from the deposit which appears in many routes, so you can't post `inverseChanneling`.
If I were you, I would attach the value `0` to the deposit and treat it specifically.
For instance, you can declare `succs` and `preds` (array of) variables and post `allDifferentExcept0` constraints to allow multiple occurrences of `0` in those arrays, but force uniqueness of other values.
Then you will need to connect `succs` and `preds` which is a little more tricky, since `0` breaks the bijection expected from such relation. You will something like `inverseChannelingExcept0` which does not exist. 
You can try to formulate it either by decomposing the relation :
```
(succs[i] = j && j > 0) => preds[j] = i
(preds[j] = i && i > 0) => succs[i] = j
```
where `succs[i] = j ` can be either expressed by an `element` constraint or a table constraint.
Alternatively, I think this can be encoded with table constraints using universal value (`CT+`).

Then you can extract pauses as you already did.

Another idea would be to get inspired from the following articles/videos
https://www.researchgate.net/publication/220403483_Solving_Vehicle_Routing_Problems_Using_Constraint_Programming_and_Metaheuristics
https://www.youtube.com/watch?v=egx9ZiU9v14
https://www.pricai.org/2014/index.php/program/program-tutorials/program-tutorials-vrp


Hope that helps,
CP

**Comment by diegomartinop** [comment]
Thank you for your help!!
