### ISSUE TITLE
[BUG] ArrayIndexOutOfBoundsException when executing model.unpost() with constraints with reifications

### ISSUE THREAD

**Issue by Drisicus** [chocoteam/choco-solver#823]
**Describe the bug**
When we try to unpost a constraint [model.unpost(constraint)] that contains the reification of another constraint, there is a java "java.lang.ArrayIndexOutOfBoundsException".

**To Reproduce**

1. Create two constraints

```
        Constraint ifCst = model.arithm(minCapacity, "<", minCapacity.getUB());
        Constraint thenCst = model.arithm(capacity, "=", minCapacity);
```

2. Create a third constraint with the refication of the previous ones

`        Constraint ifThenCst = model.arithm(ifCst.reify(), "<=", thenCst.reify());`

3. Post the third constraint and solve the problem
```

        model.post(ifThenCst);
        boolean feasibleModel = model.getSolver().solve();
```

4. Unpost third constraint

`        model.unpost(ifThenCst);`

5. Unpost first and second constraint

```
        model.unpost(ifCst);
        model.unpost(thenCst);
```

**Expected behavior**
The constraints should be unpost without errors or with a controlled error.

**Possible solution**
We believe there is a bug when creating reification constraints, the reification constraint is added to the model but cannot be removed from it.
As a workaround, we have unpost the propagator constraints of the reification constraints

```
        Arrays.stream(ifCst.getPropagators()).filter(Objects::nonNull).map(Propagator::getConstraint).forEach(model::unpost);
        Arrays.stream(thenCst.getPropagators()).filter(Objects::nonNull).map(Propagator::getConstraint).forEach(model::unpost);
```

**Code example**
```

    public static void main(String[] args) {
        Model model = new Model();

        IntVar capacity = model.intVar(0, 16);
        IntVar minCapacity = model.intVar(0, 10);

        Constraint minCapacityCst = model.arithm(capacity, ">=", minCapacity);
        model.post(minCapacityCst);

        Constraint ifCst = model.arithm(minCapacity, "<", minCapacity.getUB());
        Constraint thenCst = model.arithm(capacity, "=", minCapacity);
        Constraint ifThenCst = model.arithm(ifCst.reify(), "<=", thenCst.reify());
        model.post(ifThenCst);

        boolean feasibleModel = model.getSolver().solve();
        System.out.println(feasibleModel);

        model.post(model.arithm(capacity, ">=", minCapacity.getValue()));

        model.unpost(ifThenCst);

        /* Produces: Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 32 */
        model.unpost(ifCst);
        model.unpost(thenCst);

        /* Workaround */
//        Arrays.stream(ifCst.getPropagators()).filter(Objects::nonNull).map(Propagator::getConstraint).forEach(model::unpost);
//        Arrays.stream(thenCst.getPropagators()).filter(Objects::nonNull).map(Propagator::getConstraint).forEach(model::unpost);

        model.unpost(minCapacityCst);
        model.unassociates(minCapacity);

        model.getSolver().hardReset();
    }
```

**Environment (please complete the following information):**
- Choco-solver version: 4.10.4
- JRE : 11

**Comment by dimitri-justeau** [comment]
Hello,

I am not sure whether this is not a bug or not, as a reified constraint is never posted to a model and thus not intended to be unposted. Instead, its satisfaction state is linked to a Boolean variable with a specific `ReificationConstraint` which actually posted to the model. What your workaround actually does is unposting the `ReificationConstraint` constraints created when reifying `ifCst` and `thenCst`.

What is problematic is that the current API does not offer a method to unpost the `ReificationConstraint`. One solution could be to do it through the `unpost` method of  the reified constraint, although this could also cause confusion about what is really done. @cprudhom , do you see a better way to do this ?

In all cases, if you aim is to run multiple instances of the same problem, I would recommend not only re-instantiating the variables and constraints but also the model, as reification introduces auxiliary variables and constraints. Your code will be simpler to manage, and instantiating a model is not an expensive operation.

**Comment by Drisicus** [comment]
Hello! thanks for the reply
By re-instantiating the model you mean creating the whole model a again?

Doing a "model = new Model()" and then creating the variables and the constraints?
That will be hard for us, because sometimes we create some variables and constraints, and then we try to find a feasible value for some of the variables, if there are we add a constraint to fix those values. 
Then we add other constraints that must respect that feasible values.

So creating the model a second time could be a bit hard if we have to store the values of the variables somewhere else to post them later.

**Comment by cprudhom** [comment]
That's a tricky case. 
If I look at the example, I see that you are calling `unpost(c)` on a constraint `c` that was never _posted_ to the model, but _reified_. So, it is an expected error (well, the message is not the right one, but I will change that).

Actually, calling `c.reify()` posts, in user back, a constraint `r`. 
That's probably this one you wanted to remove from the model I suppose.
Or, in other words, you want to _dereify_ a constraint, which consequently, and under certains conditions, would remove the reifying boolean variable.

**Comment by Drisicus** [comment]
Yes exactly, we wanted to unpost the reified constraint that is post in user back.
how can we do it? is there another way or is the workaround the best approach?

Thank you!

**Comment by cprudhom** [comment]
This post is just to make things clear about reification.

There is 2 ways to reify a constraint `c` :
1. calling `c.reifyWith(b)` 
2. or calling `c.reify()` which relies on `c.reifyWith(b)` where `b` is automatically created and returned. 

So, when `c.reifyWith(b)` is called, here is was is done:
1. Get `oc`, the opposition constraint of `c` and link the 2 constraints together
2. If `c` was already reified with boolvar `d` then post an equality constraint `b = d`
3. Else if `b` is instantiated to `1`, `c` is posted
4. Else if `b` is instantiated to `0`, `oc` is posted
5. Else a `ReificationConstraint` is declared and posted

So, when it comes to _unreify_ a constraint `c`, we need to pay attention to:

Let name`d` the reifying variable that need to be removed:
1. is `d` the main reifying variable?  
2. If true, then are there other variables linked to `d` with equality constraints that also reify `c`? That's might not be easy to tell (was it done on purpose?) but if so, unpost all equality constraints. This raises the question of what to do with these variables: should they be deleted or not?
3. If false, OK, that seems quite easy: find the `ReificationConstraint` and unpost it. 

There is still general questions to answer : does `d` needs to be removed from other constraints it is associated with? If so, how those constraints need to be updated? 

### More general thoughts:
Many of you want to amend a model after it has been declared and possibly processed. Even if I understand the underlying intention: to limit the creation of Java objects, which ends up taking a long time, you have to keep in mind that this is a service whose consequences can be multiple. Originally, choco-solver is not designed to be a dynamic solver, i.e. the model varies over time. It is easy to add constraints and variables even after solving has begun (although this may have an impact on the history). Removal is more complicated since, for example, a constraint to be removed may have filtered out values from the domain of a variable. 
At no time is a global inventory created, which would simplify this usage (or not).
It is probably necessary to question our API which offers this not stabilised service.

**Comment by Drisicus** [comment]
Thanks for the reply and the explanation!
